### ISSUE TITLE
Maximum number of tables viewable is limited

### ISSUE THREAD

**Issue by jlongman** [Arattian/DynamoDb-GUI-Client#1]
**Describe the bug**
I can't see the full list of tables in one region.  There are 118 tables, I'm guessing I can only see the first 100.

**To Reproduce**
1. Run dynamodb-gui-client
2. configure a dynamodb database/endpoint with 100+ tables
3. click on the table selector
4. scroll to the bottom and verify the entire list of tables is there

**Expected behavior**
The entire list should be visible but only the first 100 or so are visible.

There are no errors listed on the console.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser electron
 - Version : 3.0.10 (3.0.10) (electron?) 
 - Version: either 3b328aa116bd9e1487bc1d707c971bfc29458f2a or what was installed with npm install -g dynamodb-gui-client. which would be dynamodb-gui-client-2.0.3.tgz.

**Comment by Arattian** [comment]
![download](https://user-images.githubusercontent.com/36269636/49717481-a5067280-fc70-11e8-8c86-94dfa56564fc.png)

Table list rendered via element-ui [el-select](https://element.eleme.io/#/en-US/component/select) element and has scroll box. I rendered 150 tables and have not seen any problem there. Check if you have all 118 tables in your database.

**Comment by Arattian** [comment]
Look, this is how i get table list from dynamodb in my code.
```
try {
    data = await state.dbInstance.listTables().promise();
}
```
And the array of tableNames, which i get from response i am just storing in application state. There are no maximum number of tablenames, that i can store in selectbox. This is just GUI, it is just showing what it receives from simple dynamodb calls.

**Comment by jlongman** [comment]
So you’re not paginating?

**Comment by Arattian** [comment]
I'll try to figure out whats the problem, but i think this is not the application issue.
