### ISSUE TITLE
Please upload to GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [Arattian/DynamoDb-GUI-Client#2]
Please upload the AppImage for Linux to [GitHub Releases](https://github.com/Arattian/DynamoDb-GUI-Client/releases) rather than to Dropbox. This will make it much easier to find the download Thank you.

**Comment by Arattian** [comment]
[Release v2.0.4](https://github.com/Arattian/DynamoDb-GUI-Client/releases/tag/v2.0.4)
