### ISSUE TITLE
Exposes AWS keys and secrets

### ISSUE THREAD

**Issue by gevorggalstyan** [Arattian/DynamoDb-GUI-Client#21]
**Describe the bug**
Remote connection option shows full AWS access key id and AWS secret access key. At least the secret should be a password field

**To Reproduce**
1. Go to the initial screen
2. Click on Remote tab
3. Type/Paste your AWS access key id and AWS secret access key in the according fields
4. Observe both of the keys being visible

**Expected behavior**
The AWS secret access key should not be visible. Instead, it should behave as a password field, ideally with a show/hide option.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: N/A
 - Version: Version 3.2.4 (3.2.4)

**Comment by Arattian** [comment]
Fixed. Now it is not visible and has show/hide option. Release will be soon.

**Comment by Arattian** [comment]
[Release 3.2.5](https://github.com/Arattian/DynamoDb-GUI-Client/releases/tag/3.2.5)
Fixes
1. Table list display bug
2. Hide/show feature for AWS secret key.
3. Table list sidebar icons removed.
