### ISSUE TITLE
Inconsistent sidebar resizing behavior

### ISSUE THREAD

**Issue by gevorggalstyan** [Arattian/DynamoDb-GUI-Client#23]
**Describe the bug**
When resizing the size bar, there is a max set. If you continue dragging the mouse gets far from the line, when you move it back the sidebar starts to resize back, the cursor being far from sidebar resize line.

**To Reproduce**
Resize the sidebar to far right and back without releasing the mouse button.

**Expected behavior**
The sidebar should wait for the mouse cursor to get back on the line before shrinking back.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: N/A
 - Version: Version 3.2.4 (3.2.4)

**Comment by Arattian** [comment]
[Release 3.3.0](https://github.com/Arattian/DynamoDb-GUI-Client/releases/tag/3.3.0)
