### ISSUE TITLE
Sidebar icons sizing inconsistency

### ISSUE THREAD

**Issue by gevorggalstyan** [Arattian/DynamoDb-GUI-Client#24]
**Describe the bug**
When connected to a database with long table names the table icons in front of the lines have random small or big (and in between) sizes.

**To Reproduce**
1. Connect to a database
2. Create tables with short and long (very long, 2 lines or more) names
3. If not visible immediately, try to resize the sidebar
4. Observe smaller icons in front of tables with longer names and bigger icons for tables with shorter names.

**Expected behavior**
The icons should have the same size for all of the lines.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: N/A
 - Version: Version 3.2.4 (3.2.4)

**Additional context**
The icons are not really needed. Try removing them.

**Comment by Arattian** [comment]
Fixed.
Icons removed.
