### ISSUE TITLE
Ability to change local url

### ISSUE THREAD

**Issue by natebrunette** [Arattian/DynamoDb-GUI-Client#28]
**Is your feature request related to a problem? Please describe.**
The local tab only supports localhost. Using localstack, the location of dynamo could be behind a different url.

**Describe the solution you'd like**
Allow setting the url in the local tab.

**Describe alternatives you've considered**

**Additional context**

**Comment by mlakmal** [comment]
i am looking for this support as well. we have our own dynamodb server internally.

**Comment by Arattian** [comment]
[Release 3.3.0](https://github.com/Arattian/DynamoDb-GUI-Client/releases/tag/3.3.0a)
