### ISSUE TITLE
How are you supposed to specify a region and access key for a local dynamodb?

### ISSUE THREAD

**Issue by npahucki** [Arattian/DynamoDb-GUI-Client#32]
I see no options for specifying anything other than the endpoint.

**Comment by Arattian** [comment]
@npahucki  As i know that you can easily connect to local db with only specifying endpoint, so i am putting some random access key in code while connecting to local database. I faced no issues with connecting to local database with such access keys. Is there something that i missed?

**Comment by npahucki** [comment]
Yes, you missed the fact that if code is configured to use a specific region which is not the default for local DynamoDB (unfortunately the region is sometimes hard coded) then upon connecting you need to specify the region or you will NOT see the tables at all because local dynamodb scopes the data by the access key and the region. For that matter, in addition to allowing the region to be specified, you should also allow the access key to be specified for the same reason. 

See https://aws.amazon.com/blogs/aws/dynamodb-local-for-desktop-development/

"DynamoDB Local will create a local database in the same directory as the JAR. The file name will have the form MyAccessKeyId_Region.db, where MyAccessKeyId is the AWS access key used to access DynamoDB Local and Region is the target region."

**Comment by Arattian** [comment]
@npahucki Thank you for sharing, i'll try to implement this in next release.
