### ISSUE TITLE
Question: Rewrite in progress

### ISSUE THREAD

**Issue by dwelch2344** [Arattian/DynamoDb-GUI-Client#48]
Hey there! 

Just pulled this down and started tinkering, and it's great! The project works great for our simple usecase, but it's also built with tech we're familiar with and we'd love to contribute. 

I saw in #34 you mentioned a rewrite's in progress, so we don't want to jump in and rock the boat / contribute to the wrong places. Any chance you could give us some visibility into that, or even want some additional help on it?

**Comment by Arattian** [comment]
Thank you for your interest. Actually, I am a little busy these days with other work I have, but rewriting will not be a hard process. I'll ask for your help if I stuck somewhere. But for now, codes are too scattered and not shareable. Thank you again for your help offer I really appreciate it.
