### ISSUE TITLE
Does it support 'query' command? 

### ISSUE THREAD

**Issue by bayannur** [Arattian/DynamoDb-GUI-Client#49]
Thanks for the DynamoDb-GUI-Client, I can work on dynamodb in GUI tool. I have some questions:
1) I saw 'Scan' in the tab 'Records', does it equal to 'scan' API in DDB? Does the DynamoDb-GUI-Client support 'query'?
2) Only one filter condition in the DynamoDb-GUI-Client? Can I have more filter conditions?
3) Scan or Query only on Table? Can I  Scan or Query on GSI?
All the questions refer to AWS console.
Thanks.

**Comment by Arattian** [comment]
For now, it only supports 'Scan' and 'Yes' it is done with DynamoDb 'scan' method. I have already planned to add GSI and 'query' support in the future. Thank you.
