### ISSUE TITLE
Table row count (bottom summary view) does not update on refresh

### ISSUE THREAD

**Issue by ILAsoft** [Arattian/DynamoDb-GUI-Client#52]
**Describe the bug**
The current table row count (in the bottom-right summary view) does not update on refresh/change (or updates way later?)

**To Reproduce**
1. Pull table information
2. Make note of the total count of rows displayed on the very bottom right
3. Add more records to the table
4. Refresh/rescan
5. Observe more records displayed successfully, yet the count not changing

**Expected behavior**
Correct count of number of rows being displayed after refresh/rescan

**Screenshots**
![image](https://user-images.githubusercontent.com/1714445/62232996-70b90100-b37c-11e9-906d-05b713dcf18e.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox
 - Version 3.3.1

**Additional context**

**Comment by Arattian** [comment]
The only way i can show the total item count without scanning your entire table,  is to get it from table meta. Which i am doing here, unfortunately amazon does not update table ItemCount right after your actions, that's why you see  the wrong number.
