### ISSUE TITLE
Can't paste into connection setup fields

### ISSUE THREAD

**Issue by jrupp** [Arattian/DynamoDb-GUI-Client#7]
**Describe the bug**
On a Mac, Shortcut keys and right-click context menus do not work for the textboxes used to create a new database connection.

**To Reproduce**
1. Opened the application as a brand new user
1. Copy your AWS Access Key ID from where-ever you have it stored
1. Click on the "Access Key Id" text box
1. Press CMD+V on your keyboard
1. Nothing happens

**Expected behavior**
I would expect to be able to paste in my API key information instead of having to enter it manually by hand.

**Screenshots**
Since nothing happens, I don't think a screenshot would show anything...

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.2
 - Client Version 2.1.1 and 3.0.0

**Additional context**
I opened the application as a brand new user, and tried to paste my AWS Access Key ID into the text box. Pressing CMD+V did nothing.  I then tried to right click the box, but no menu appeared.  I manually entered some random characters and pressed CMD+A, and it did not select all of the text in the textbox.

I tried this in the Access Key ID, Secret Access Key, and Database Name fields.  None of them allowed me to paste or Select All using keyboard shortcuts, nor did they allow me to right click to get a context menu.

I tried this in both version 2.1.1 and 3.0.0 on a MacBook Pro running macOS Mojave 10.14.2

**Comment by Arattian** [comment]
Will be fixed in next release.

**Comment by Arattian** [comment]
Will be fixed in next release.

**Comment by Arattian** [comment]
[Fixed in v.3.1.0
](https://github.com/Arattian/DynamoDb-GUI-Client/releases/download/3.1.0/DynamoDbGUI-mac-3.1.0.dmg)
